export const ADD_TODO = 'todo/add_todo'
export const TOGGLE_TODO = 'todo/toggle_todo'
export const DELETE_TODO = 'todo/delete_todo'
export const COMPLETE_ALL_TODO = 'todo/complete_all_todo'
export const DELETE_COMPLETED_TODO = 'todo/delete_completed_todo'
export const CHANGE_TODO_COLOR = 'todo/change_todo_color'
